# Coding Session #2

---

## Today's session

Today's session is structured to progressively introduce you to more advance Python features. We will explore:

- String methods (with a focus on `.replace()`)
- Type casting
- Importing modules and functions (using the `math` library)
- Intro to Pandas and merging

### 1. String methods and `.replace()`

The `.replace()` method is particularly useful for substituting occurrences of a specified substring within a string with another substring. It's a non-destructive operation, meaning it returns a *new* string with the replacements made, leaving the original string unchanged. This is a crucial concept in Python: many string methods return new strings rather than modifying the original in place.

**Syntax:** `string.replace(old, new[, count])`

- `old`: The substring you want to replace.
- `new`: The substring you want to replace `old` with.
- `count` (optional): An integer specifying the maximum number of occurrences to replace. If omitted, all occurrences are replaced.

Let's explore this with examples to truly understand its versatility.

#### Basic Replacement

Imagine you have a sentence and you want to correct a misspelled word.



In [ ]:
original_sentence = "I love pythn programming."
corrected_sentence = original_sentence.replace("pythn", "Python")
print(f"Original: {original_sentence}")
print(f"Corrected: {corrected_sentence}")

Original: I love pythn programming.
Corrected: I love Python programming.



#### Replacing all occurrences

Consider a scenario where you need to standardize certain terms in a document. The `.replace()` method, by default, replaces all instances of the `old` substring.



In [ ]:
text_data = "The quick brown fox jumps over the lazy dog. The fox is very quick."
modified_text = text_data.replace("fox", "cat")
print(f"Original: {text_data}")
print(f"Modified: {modified_text}")


Original: The quick brown fox jumps over the lazy dog. The fox is very quick.
Modified: The quick brown cat jumps over the lazy dog. The cat is very quick.



#### Other useful string methods

While `.replace()` is powerful, many other string methods are equally important for text manipulation:

- `.upper()` / `.lower()`: Convert string to uppercase/lowercase.
- `.strip()`: Remove leading/trailing whitespace.
- `.split()`: Split a string into a list of substrings based on a delimiter.
- `.find()` / `.index()`: Find the first occurrence of a substring.
- `.startswith()` / `.endswith()`: Check if a string starts/ends with a specified prefix/suffix.

Some useful examples:

.strip() returns a new string with spaces, tabs, and newlines removed from both ends (not the middle).



In [ ]:
raw_text = "  \n  Ada Lovelace \t  "
clean_text = raw_text.strip()
print(clean_text)        # 'Ada Lovelace'


Ada Lovelace



.find() locate a substring and return the position of the first occurrence of a substring. T



In [ ]:
email = "ada@university.edu"
at = email.find("@")
print(at)
domain = email[at+1:]
print(domain)



3
university.edu



## 2. Converting to and from strings (type casting)

In Python, every piece of data has a specific *type*. For instance, `5` is an integer (`int`), `3.14` is a floating-point number (`float`), and `"hello"` is a string (`str`). Understanding data types is fundamental because different types behave differently and support different operations. For example, you can perform arithmetic operations on numbers, but not directly on strings (e.g., `"5" + "2"` results in `"52"`, not `7`).

**Type casting** (or type conversion) is the process of converting a value from one data type to another. This is a very common operation, especially when dealing with user input (which is often read as a string) or when preparing data for specific operations.

### Converting to a string (`str()`)

The `str()` function is used to convert values of other data types into strings. This is particularly useful when you want to concatenate (join) numbers or other data with text, or when you need to store non-string data in a text-based format.

#### Converting numbers to strings

Let's say you want to display a message that includes a numerical value.



In [ ]:
age = 20
message = "I am " + str(age) + " years old."
print(message)

pi_value = 3.14159
pi_message = "The value of Pi is approximately " + str(pi_value) + "."
print(pi_message)


I am 20 years old.
The value of Pi is approximately 3.14159.



### Converting from a string (`int()`, `float()`)

Conversely, you often receive data as strings (e.g., from user input, file reading, or web scraping) that you need to treat as numbers. Python provides `int()` for converting to integers and `float()` for converting to floating-point numbers.

Consider a scenario where a user inputs their age or a price.



In [ ]:
user_age_str = "25"
user_age_int = int(user_age_str)
print(f"User's age (as integer): {user_age_int}, Type: {type(user_age_int)}")

item_price_str = "19.99"
item_price_float = float(item_price_str)
print(f"Item price (as float): {item_price_float}, Type: {type(item_price_float)}")

# You can now perform arithmetic operations
total_cost = item_price_float * 2
print(f"Total cost for two items: {total_cost}")


User's age (as integer): 25, Type: <class 'int'>
Item price (as float): 19.99, Type: <class 'float'>
Total cost for two items: 39.98



## 3. Importing modules and dunctions

One of Python's greatest strengths lies in its vast ecosystem of modules and packages. A **module** is simply a file containing Python definitions and statements. By importing modules, you can access pre-written functions, classes, and variables, avoiding the need to write everything from scratch. This promotes code reusability, organization, and efficiency.

### The `import` statement

The `import` statement is used to bring modules into your current Python script or interactive session. Once imported, you can access the module's contents using the dot notation (`module_name.function_name`).

**Syntax:** `import module_name`

#### Importing the `math` module

The `math` module provides access to mathematical functions defined by the C standard. It includes functions for trigonometry, logarithms, powers, and constants like Pi.



In [ ]:
import math

# Accessing functions and constants from the math module
radius = 5
area_of_circle = math.pi * (radius ** 2)
print(f"Area of circle with radius {radius}: {area_of_circle}")

# Using math.sqrt() for square root
number = 64
square_root = math.sqrt(number)
print(f"Square root of {number}: {square_root}")

# Using math.cos() for cosine (angle in radians)
angle_degrees = 60
angle_radians = math.radians(angle_degrees) # Convert degrees to radians
cosine_value = math.cos(angle_radians)
print(f"Cosine of {angle_degrees} degrees: {cosine_value}")


Area of circle with radius 5: 78.53981633974483
Square root of 64: 8.0
Cosine of 60 degrees: 0.5000000000000001



### Alternative import forms

Python offers several ways to import modules or specific components from them:

- `import module_name as alias`: Imports the module but gives it a shorter alias for convenience. This is common for libraries like NumPy (`import numpy as np`).
- `from module_name import function_name`: Imports only specific functions or variables from a module, allowing you to use them directly without the `module_name.` prefix.
- `from module_name import *`: Imports all public names from a module directly into the current namespace. **(Caution: This is generally discouraged in larger projects as it can lead to name clashes and make code harder to read and debug.)**

#### Using `from ... import ...`

If you only need a few specific functions from a module, this can make your code cleaner.



In [ ]:
from math import sqrt, pi

# Now you can use sqrt and pi directly
hypotenuse = sqrt(3**2 + 4**2)
print(f"Hypotenuse of a 3-4-5 triangle: {hypotenuse}")

circumference = 2 * pi * 7
print(f"Circumference of a circle with radius 7: {circumference}")


Hypotenuse of a 3-4-5 triangle: 5.0
Circumference of a circle with radius 7: 43.982297150257104



**Tip:** When possibile, start with `from module_name import function_name` unless you have a good reason to do otherwise. It keeps your code clear and avoids surprises.

## 4. Merging data

In real-world data analysis, information is rarely confined to a single table or file. Often, you'll encounter scenarios where relevant data is spread across multiple sources, and you need to combine them to gain a complete picture. The process of combining data based on common columns or keys is known as **merging** or **joining**.

While NumPy is excellent for numerical operations on single arrays, for structured data (like tables with columns and rows, similar to spreadsheets), the **Pandas** library is the go-to tool in Python. Pandas builds on NumPy and provides powerful data structures like `DataFrame`s, which are ideal for tabular data.

### Introduction to Pandas `DataFrame` (brief)

A Pandas `DataFrame` can be thought of as a spreadsheet or a SQL table. It's a 2-dimensional labeled data structure with columns of potentially different types. You can create DataFrames from dictionaries, lists of lists, or by reading data from files (CSV, Excel, etc.). We’ll be using pandas throughout the course, so you’ll have plenty of chances to learn more."

### The `pd.merge()` function

The `pd.merge()` function is the primary way to combine DataFrames based on common columns. It's conceptually similar to SQL JOIN operations.

**Syntax:** `pd.merge(left, right, on=None, how='inner')`

- `left`: The first DataFrame to merge.
- `right`: The second DataFrame to merge.
- `on`: (Optional) Column or list of columns to join on. If `None`, it defaults to the intersection of column names in `left` and `right`.
- `how`: (Optional) Type of merge to be performed. Common types include:
    - `'inner'` (default): Use intersection of keys from both frames.
    - `'left'` (left outer join): Use keys from left frame.
    - `'right'` (right outer join): Use keys from right frame.
    - `'outer'` (full outer join): Use union of keys from both frames.

**Tip (very important):** The column name(s) specified in `on` must exist with the same name in both DataFrames. If the key names differ, the merge will not suceeded. u

#### Inner merge

Let's say we have two DataFrames: one with student IDs and names, and another with student IDs and their scores. We want to combine them to get student names along with their scores.



In [ ]:
import pandas as pd

# DataFrame 1: Student Names
students_df = pd.DataFrame({
  "student_id": [101, 102, 103, 104],
  "name": ["Alice", "Bob", "Charlie", "David"]
})

# DataFrame 2: Student Scores
scores_df = pd.DataFrame({
  "student_id": [101, 103, 104, 105],
  "score": [85, 92, 78, 95]
})

print("Students DataFrame:")
print(students_df)
print("\nScores DataFrame:")
print(scores_df)

# Perform an inner merge
merged_df_inner = pd.merge(students_df, scores_df, on="student_id", how="inner")
print("\nInner Merged DataFrame (only common student_ids):")
print(merged_df_inner)


Students DataFrame:
   student_id     name
0         101    Alice
1         102      Bob
2         103  Charlie
3         104    David

Scores DataFrame:
   student_id  score
0         101     85
1         103     92
2         104     78
3         105     95

Inner Merged DataFrame (only common student_ids):
   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
2         104    David     78



#### Left, right, and outer merges

The `how` argument dictates which keys to include in the merged DataFrame:

-   **Left Merge (`how='left'`):** Includes all rows from the left DataFrame and matching rows from the right. If there's no match in the right DataFrame, `NaN` (Not a Number) is filled for the columns from the right DataFrame.
-   **Right Merge (`how='right'`):** Includes all rows from the right DataFrame and matching rows from the left. If there's no match in the left DataFrame, `NaN` is filled for the columns from the left DataFrame.
-   **Outer Merge (`how='outer'`):** Includes all rows from both DataFrames. Where there are no matching values, `NaN` is filled.

**Tip** The logic of merge can be tricky to remember at first. If you’re unsure, use `help(pd.merge)` to quickly check how it works.


## Error Safari

**1. Wrong data type**



In [ ]:
number = 2025

# Bad: AttributeError (int has no attribute 'replace')
# wrong = number.replace("2", "9")

# Good: Convert the integer to a string first
fixed = str(number).replace("2", "9")
print(fixed)     # '9095'


9095



**2. Adding strings instead of numbers**




In [ ]:
num1 = "5"
num2 = "2"

# Bad: This doesn’t crash, but it gives the wrong result
wrong_sum = num1 + num2
print(wrong_sum)   # '52' instead of 7

# Good: Convert strings to integers first
right_sum = int(num1) + int(num2)
print(right_sum)   # 7


52
7



**3. Converting an invalid string to a number**




In [ ]:
price_str = "19.99 dollars"

# Bad: ValueError (invalid literal for int/float)
# price_num = float(price_str)

# Good: The string must contain only digits (and at most one decimal point)
price_str_clean = "19.99"
price_num = float(price_str_clean)
print(price_num * 2)   # 39.98


39.98



**4. Assigned variables are immutable**



In [ ]:
msg = "hello world"

#bad: expecting msg to change
msg.replace("world", "Python")
print(msg)   # still "hello world" !

# Good: assign the result to a new variable
new_msg = msg.replace("world", "Python")
print(new_msg)


hello world
hello Python



**5. Using an alias incorrectly**



In [ ]:
import math as m

# Bad: NameError (math is not defined)
# print(math.sqrt(25))

# Good: Use the alias consistently
print(m.sqrt(25))


5.0



**6. Key names differ in pd.merge**




In [ ]:
students_df = pd.DataFrame({
    "student_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"]
})

scores_df = pd.DataFrame({
    "id": [101, 103, 104],
    "score": [85, 92, 78]
})

# Bad KeyError (student_id not found in right DataFrame)
# merged = pd.merge(students_df, scores_df, on="student_id")

# Good #1: Rename the column

scores_df_r = scores_df.rename(columns={"id": "student_id"})
merged_1 = pd.merge(students_df, scores_df_r, on="student_id")
print(merged_1)

# Good #2: use left_on / right_on
merged_2 = pd.merge(students_df, scores_df, left_on="student_id", right_on="id")
print(merged_2)



   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
   student_id     name   id  score
0         101    Alice  101     85
1         103  Charlie  103     92



**7. Using the wrong merge type**



In [ ]:
students_df = pd.DataFrame({
    "student_id": [101, 102],
    "name": ["Alice", "Bob"]
})
scores_df = pd.DataFrame({
    "student_id": [201, 202],
    "score": [85, 90]
})

# Bad: Inner merge gives empty DataFrame (no common IDs)
merged_inner = pd.merge(students_df, scores_df, on="student_id", how="inner")
print(merged_inner)   # Empty!

# Good: Use outer merge if you want to keep all data
merged_outer = pd.merge(students_df, scores_df, on="student_id", how="outer")
print(merged_outer)


Empty DataFrame
Columns: [student_id, name, score]
Index: []
   student_id   name  score
0         101  Alice    NaN
1         102    Bob    NaN
2         201    NaN   85.0
3         202    NaN   90.0



## Exercise: Merge Sales Data

Practice merging two DataFrames with `pd.merge`, and understand how how='left', 'right', and 'outer' change the result. Answer these questions (you do not need any coding for answering these):

- In the left merge, why does student_id=102 have score=NaN?
- In the right merge, why does student_id=105 have name=NaN?
- In the outer merge, which IDs came from only one side?
- How many rows are perfect matches (non-missing name and score)?



In [ ]:
students_df = pd.DataFrame({
  "student_id": [101, 102, 103, 104],
  "name": ["Alice", "Bob", "Charlie", "David"]
})
scores_df = pd.DataFrame({
  "student_id": [101, 103, 104, 105],
  "score": [85, 92, 78, 95]
})

# Left merge
merged_df_left = pd.merge(students_df, scores_df, on="student_id", how="left")
print("\nLeft Merged DataFrame (all students from left, matching scores):")
print(merged_df_left)

# Right merge
merged_df_right = pd.merge(students_df, scores_df, on="student_id", how="right")
print("\nRight Merged DataFrame (all scores from right, matching students):")
print(merged_df_right)

# Outer merge
merged_df_outer = pd.merge(students_df, scores_df, on="student_id", how="outer")
print("\nOuter Merged DataFrame (all students and all scores):")
print(merged_df_outer)



Left Merged DataFrame (all students from left, matching scores):
   student_id     name  score
0         101    Alice   85.0
1         102      Bob    NaN
2         103  Charlie   92.0
3         104    David   78.0

Right Merged DataFrame (all scores from right, matching students):
   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
2         104    David     78
3         105      NaN     95

Outer Merged DataFrame (all students and all scores):
   student_id     name  score
0         101    Alice   85.0
1         102      Bob    NaN
2         103  Charlie   92.0
3         104    David   78.0
4         105      NaN   95.0



**Answers:**

- Because 102 exists only in students_df (left table) and not in scores_df, so score is missing.
- Because 105 exists only in scores_df (right table) and not in students_df, so name is missing.
- From left only: 102. From right only: 105.
- 3 rows: IDs 101, 103, 104.

# Congratulations!

You are done with the coding session. Questions or suggestions? Email Alberto at alberto.stefanelli@yale.edu.



In [ ]:
# Install requirements
!apt-get -qq update
!apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

from google.colab import drive, files

# Mount Google Drive
drive.mount('/content/drive')

# Ask for the notebook name
notebook_name = input(
    "Enter your notebook’s exact file name,\n"
    "exactly as shown in the top-left corner of the Colab page (next to the two yellow circle icons): "
)

# Build paths
input_path = f"/content/drive/MyDrive/Colab Notebooks/{notebook_name}"
output_path = input_path.replace(".ipynb", ".pdf")

# Convert to PDF
!jupyter nbconvert --to pdf "{input_path}"

# Download the PDF
files.download(output_path)

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dvisvgm fonts-droid-fallback fonts-lato fonts-lmodern fonts-noto-mono
  fonts-texgyre fonts-urw-base35 libapache-pom-java
  libcmark-gfm-extensions0.29.0.gfm.3 libcmark-gfm0.29.0.gfm.3
  libcommons-logging-java libcommons-parent-java libfontbox-java libgs9
  libgs9-common libidn12 libijs-0.35 libjbig2dec0 libkpathsea6 libpdfbox-java
  libptexenc1 libruby3.0 libsynctex2 libteckit0 libtexlua53 libtexluajit2
  libwoff1 libzzip-0-13 lmodern pandoc-data poppler-data preview-latex-style
  rake ruby ruby-net-telnet ruby-rubygems ruby-webrick ruby-xmlrpc ruby3.0
  rubygems-integration t1utils teckit tex-common tex-gyre texlive-base
  texlive-binaries texlive-

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>